name: "CI Tests"

on:
  push:
    branches: "master"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2"]
        rails: ["6.1", "7.0", "7.1"]
        include:
          - ruby: "3.3"
            rails: "main"

    env:
      RAILS_ENV: "test"
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
    - uses: "actions/checkout@v1"

    - name: "Install NodeJS 18.x"
      uses: "actions/setup-node@v1"
      with:
        node-version: "18.x"

    - name: "Install Ruby ${{ matrix.ruby }}"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: "Generate lockfile"
      run: |
        bundle config path vendor/bundle
        bundle lock

    - name: "Cache Ruby dependencies"
      uses: "actions/cache@v1"
      with:
        path: "vendor/bundle"
        key: bundle-${{ hashFiles('Gemfile.lock') }}

    - name: "Install Webdriver"
      run: |
        sudo apt-get update
        sudo apt-get -yqq install chromium-browser

    - name: "Run Setup"
      run: |
        bin/setup

    - name: "Run Tests"
      run: |
        bin/rake
