name: "CI Tests"

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        rails: ["6.1", "7.0", "7.1", "7.2"]
        include:
          - ruby: "3.3"
            rails: "main"

    env:
      RAILS_ENV: "test"
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
    - uses: "actions/checkout@v4"

    - name: "Install NodeJS"
      uses: "actions/setup-node@v4"
      with:
        node-version: "20.x"

    - name: "Install Ruby ${{ matrix.ruby }}"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: "Install Webdriver"
      run: |
        sudo apt-get update
        sudo apt-get -yqq install chromium-browser

    - name: "Run Setup"
      run: |
        bin/setup

    - name: "Run Tests"
      run: |
        bin/rake
